In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import os

In [14]:
years = list(range(2013,2024))

In [3]:
url_start = "https://www.basketball-reference.com/awards/awards_{}.html"

In [5]:
os.makedirs("mvp", exist_ok=True)  # ‚Üê Esto crea la carpeta si no existe

In [7]:
for year in years:
    url = url_start.format(year)
    
    data = requests.get(url)
    
    with open("mvp/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)

In [4]:
with open("mvp/2013.html", encoding="utf-8") as f:
    page = f.read()
    
soup = BeautifulSoup(page, 'html.parser')
soup.find('tr', class_="over_header").decompose()

In [5]:
mvp_table = soup.find_all(id="mvp")[0]

In [11]:
mvp_2013 = pd.read_html(str(mvp_table))[0]

C:\Users\manus\AppData\Local\Temp\ipykernel_8188\1916762463.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  mvp_2013 = pd.read_html(str(mvp_table))[0]

In [12]:
mvp_2013

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,LeBron James,28,MIA,120,1207,1210,0.998,76,37.9,26.8,8.0,7.3,1.7,0.9,0.565,0.406,0.753,19.3,0.322
1,2,Kevin Durant,24,OKC,0,765,1210,0.632,81,38.5,28.1,7.9,4.6,1.4,1.3,0.510,0.416,0.905,18.9,0.291
2,3,Carmelo Anthony,28,NYK,1,475,1210,0.393,67,37.0,28.7,6.9,2.6,0.8,0.5,0.449,0.379,0.830,9.5,0.184
3,4,Chris Paul,27,LAC,0,289,1210,0.239,70,33.4,16.9,3.7,9.7,2.4,0.1,0.481,0.328,0.885,13.9,0.287
4,5,Kobe Bryant,34,LAL,0,184,1210,0.152,78,38.6,27.3,5.6,6.0,1.4,0.3,0.463,0.324,0.839,10.9,0.174
5,6,Tony Parker,30,SAS,0,86,1210,0.071,66,32.9,20.3,3.0,7.6,0.8,0.1,0.522,0.353,0.845,9.3,0.206
6,7,Tim Duncan,36,SAS,0,65,1210,0.054,69,30.1,17.8,9.9,2.7,0.7,2.7,0.502,0.286,0.817,8.3,0.191
7,8,James Harden,23,HOU,0,33,1210,0.027,78,38.3,25.9,4.9,5.8,1.8,0.5,0.438,0.368,0.851,12.8,0.206
8,9,Russell Westbrook,24,OKC,0,9,1210,0.007,82,34.9,23.2,5.2,7.4,1.8,0.3,0.438,0.323,0.800,11.6,0.195
9,10,Dwyane Wade,31,MIA,0,5,1210,0.004,69,34.7,21.2,5.0,5.1,1.9,0.8,0.521,0.258,0.725,9.6,0.192
10,11,Stephen Curry,24,GSW,0,3,1210,0.002,78,38.2,22.9,4.0,6.9,1.6,0.2,0.451,0.453,0.900,11.2,0.180
11,12T,Kevin Garnett,36,BOS,0,1,1210,0.001,68,29.7,14.8,7.8,2.3,1.1,0.9,0.496,0.125,0.786,5.6,0.133
12,12T,Marc Gasol,28,MEM,0,1,1210,0.001,80,35.0,14.1,7.8,4.0,1.0,1.7,0.494,0.071,0.848,11.5,0.197
13,12T,Ty Lawson,25,DEN,0,1,1210,0.001,73,34.4,16.7,2.7,6.9,1.5,0.1,0.461,0.366,0.756,7.4,0.141
14,12T,David Lee,29,GSW,0,1,1210,0.001,79,36.8,18.5,11.2,3.5,0.8,0.3,0.519,0.000,0.797,9.1,0.150
15,12T,Joakim Noah,27,CHI,0,1,1210,0.001,66,36.8,11.9,11.1,4.0,1.2,2.1,0.481,0.000,0.751,7.3,0.145

In [16]:
dfs = []
for year in years:
    with open("mvp/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="over_header").decompose()
    mvp_table = soup.find_all(id="mvp")[0]
    mvp_df = pd.read_html(str(mvp_table))[0]
    mvp_df["Year"] = year
    dfs.append(mvp_df)

C:\Users\manus\AppData\Local\Temp\ipykernel_8188\3892927945.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  mvp_df = pd.read_html(str(mvp_table))[0]
C:\Users\manus\AppData\Local\Temp\ipykernel_8188\3892927945.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  mvp_df = pd.read_html(str(mvp_table))[0]
C:\Users\manus\AppData\Local\Temp\ipykernel_8188\3892927945.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  mvp_df = pd.read_html(str(mvp_table))[0]
C:\Users\manus\AppData\Local\Temp\ipykernel_8188\3892927945.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  mvp_df = pd.read_html(str(mvp_table))[0]
C:\Users\manus\AppData\Local\Temp\ipykernel_8188\3892927945.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  mvp_df = pd.read_html(str(mvp_table))[0]
C:\Users\manus\AppData\Local\Temp\ipykernel_8188\3892927945.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  mvp_df = pd.read_html(str(mvp_table))[0]
C:\Users\manus\AppData\Local\Temp\ipykernel_8188\3892927945.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  mvp_df = pd.read_html(str(mvp_table))[0]
C:\Users\manus\AppData\Local\Temp\ipykernel_8188\3892927945.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  mvp_df = pd.read_html(str(mvp_table))[0]
C:\Users\manus\AppData\Local\Temp\ipykernel_8188\3892927945.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  mvp_df = pd.read_html(str(mvp_table))[0]
C:\Users\manus\AppData\Local\Temp\ipykernel_8188\3892927945.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  mvp_df = pd.read_html(str(mvp_table))[0]
C:\Users\manus\AppData\Local\Temp\ipykernel_8188\3892927945.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  mvp_df = pd.read_html(str(mvp_table))[0]

In [17]:
mvps = pd.concat(dfs)

In [20]:
mvps.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,LeBron James,28,MIA,120,1207,1210,0.998,76,37.9,...,8.0,7.3,1.7,0.9,0.565,0.406,0.753,19.3,0.322,2013
1,2,Kevin Durant,24,OKC,0,765,1210,0.632,81,38.5,...,7.9,4.6,1.4,1.3,0.510,0.416,0.905,18.9,0.291,2013
2,3,Carmelo Anthony,28,NYK,1,475,1210,0.393,67,37.0,...,6.9,2.6,0.8,0.5,0.449,0.379,0.830,9.5,0.184,2013
3,4,Chris Paul,27,LAC,0,289,1210,0.239,70,33.4,...,3.7,9.7,2.4,0.1,0.481,0.328,0.885,13.9,0.287,2013
4,5,Kobe Bryant,34,LAL,0,184,1210,0.152,78,38.6,...,5.6,6.0,1.4,0.3,0.463,0.324,0.839,10.9,0.174,2013

In [21]:
mvps.to_csv("mvps.csv")